### ISSUE TITLE
script08 Documentation/setup

### ISSUE THREAD

**Issue by anerv** [anastassiavybornova/bike-node-planner#54]
Right now the layers used for the different map exports in script08 are hard-coded and the script will fail if these layers for some reason are not generated.

Should this be modified and/or pointed out in the documentation?

**Comment by anastassiavybornova** [comment]
...and lastly: i'm already working on a separate branch on a solution for script07 for that (and also for #25 , #27 )

**Comment by anerv** [comment]
awesome - I'll find a solution for script08 :)
